name: Build iOS

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-ios.yml"
      - "ios/**"
      - "*.podspec"
  pull_request:
    paths:
      - ".github/workflows/build-ios.yml"
      - "ios/**"
      - "*.podspec"

jobs:
  validate:
    name: Validate iOS podspec
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install
