name: Validate JS

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/validate-js.yml"
      - "src/**"
      - "*.json"
      - "*.js"
      - "*.lock"
  pull_request:
    paths:
      - ".github/workflows/validate-js.yml"
      - "src/**"
      - "*.json"
      - "*.js"
      - "*.lock"

jobs:
  compile:
    name: Compile JS (tsc)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Run TypeScript # Reviewdog tsc errorformat: %f:%l:%c - error TS%n: %m
        run: |
          bun typescript | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint JS (eslint, prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Run ESLint
        run: bun lint-ci

      - name: Run ESLint with auto-fix
        run: bun run lint

      - name: Verify no files have changed after auto-fix
        run: git diff --exit-code HEAD
